---
title: "wk4_homework"
output: html_document
date: "2025-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in files

```{r}
library(sf)
world_shapes <- st_read('~/Documents/CASA/GIS/wk4/hw4/World_Countries.geojson')
```

```{r}
library(tidyverse)
gender_inequity_data <- read_csv('~/Documents/CASA/GIS/wk4/hw4/HDR25_Composite_indices_complete_time_series.csv')
```

Add correct country code to inequality data
```{r}
library(countrycode)

iso_world <- mutate(
  gender_inequity_data,
  ISO = countrycode(
    gender_inequity_data$iso3,
    origin="iso3c",
    destination = "iso2c"
  )
)
```



Which countries are left out of the gender inequality dataset?
```{r}
filter(world_shapes, !ISO %in% gender_inequity_data$iso3)$COUNTRY
```

# Join data

```{r}
joined_data <- left_join(
  world_shapes,
  iso_world,
  by = join_by(ISO == ISO)
)
```


# Create new column

```{r}
needed_columns = c("ISO", "COUNTRY", "gii_2010", "gii_2019", "geometry")
final_data <- mutate(
  joined_data[,needed_columns],
  difference_in_inequality=gii_2019-gii_2010
)
```

# Plot data

```{r}
library(tmap)

tmap_mode("view")
tm_shape(final_data) +
  tm_basemap(server = "OpenStreetMap") +
  tm_compass(type = "arrow", position = c("left", "bottom")) +
  tm_scalebar(position = c("left", "bottom")) +
  tm_title("Difference in Gender Inequality 2010-2019") +
  tm_polygons(fill="difference_in_inequality",
              fill_alpha=0.8,
              fill.legend = tm_legend(title = "Difference in Inequality", 
                                      size = 0.8))
```

```{r}

library(tmap)
library(viridis)  # optional, tmap can use viridis palettes directly

# Set interactive mode
tmap_mode("view")

# Create a map using the 'magma' Viridis palette
tm_shape(final_data) +
  tm_basemap(server = "OpenStreetMap") +
  tm_compass(type = "arrow", position = c("left", "bottom")) +
  tm_scalebar(position = c("left", "bottom")) +
  tm_title("Gender Inequality Change 2010-2019") +
  tm_polygons(
    col = "difference_in_inequality",   # variable to color polygons
    palette = "magma",                   # use Viridis 'magma' palette
    style = "jenks",                     # natural breaks classification
    alpha = 0.8,                         # transparency
    border.col = "gray50",               # polygon border
    title = "Difference in Inequality"
  )


```

